import {productSlug,servicePages} from './data/seoContent';
export const defaultSiteUrl='https://www.curvadenim.com';
const basePages={
 '/':['Denim Fabric Supplier for Brands & Garment Factories | Curva Fabric','B2B rigid, stretch, lightweight and specialty denim fabrics with swatches, technical data and mill-direct sourcing support.'],
 '/products':['Denim Fabric Library | Curva Fabric','Explore rigid, stretch, lightweight, black, ecru and recycled-content denim by composition, weight, weave and end use.'],
 '/about':['Denim Mill & Fabric Supply Partner | Curva Fabric','Meet the fabric team connecting quality development, sampling, testing, bulk production and export coordination.'],
 '/news-blog/':['Denim Fabric Sourcing Insights | Curva Fabric','Practical guidance on denim weight, weave, stretch, shrinkage, wash development, testing and bulk fabric sourcing.'],
 '/faq':['Denim Fabric Sourcing FAQ | Curva Fabric','Answers about fabric MOQ, swatches, technical data, custom development, testing, production and shipping.'],
 '/contact':['Request Denim Swatches & Fabric Quote | Curva Fabric','Send your denim fabric brief to request relevant swatches, technical sheets, MOQ, lead time and a mill quotation.']
};
const privatePages={'/login':['Buyer Account Sign In | Curva Fabric','Sign in to build fabric RFQs and continue sourcing conversations.'],'/quote':['Build a Fabric RFQ | Curva Fabric','Private multi-quality fabric RFQ workspace.'],'/admin':['Product Admin | Curva Fabric','Private product administration.'],'/admin/users':['User Admin | Curva Fabric','Private user administration.'],'/admin/roles':['Role Admin | Curva Fabric','Private role administration.'],'/admin/articles':['Fabric Insight Admin | Curva Fabric','Private editorial workspace.'],'/admin/faqs':['FAQ Admin | Curva Fabric','Private FAQ workspace.'],'/support/inbox':['Buyer Support Inbox | Curva Fabric','Private fabric support workspace.']};
export function normalizeSeoPath(pathname='/'){if(pathname==='/news-blog'||pathname==='/news-blog/')return '/news-blog/';return pathname.length>1&&pathname.endsWith('/')?pathname.slice(0,-1):pathname}
export function buildPublicSeoPaths(products=[],articles=[]){return [...Object.keys(basePages),...products.map(p=>`/products/${productSlug(p)}`),...Object.keys(servicePages).map(s=>`/services/${s}`),...articles.map(a=>`/news-blog/${a.slug}`)]}
export function buildPrerenderPaths(products=[],articles=[]){return [...buildPublicSeoPaths(products,articles),...Object.keys(privatePages),'/404']}
export function getSeoForPath(pathname='/',products=[],articles=[]){const path=normalizeSeoPath(pathname);const defaults={path,canonical:path,image:'/fabric/hero-denim-mill.png',type:'website',noindex:false};if(basePages[path])return {...defaults,title:basePages[path][0],description:basePages[path][1],schemaType:path==='/'||path==='/about'?'organization':'webpage'};if(privatePages[path])return {...defaults,title:privatePages[path][0],description:privatePages[path][1],noindex:true};const pm=path.match(/^\/products\/(.+)$/);if(pm){const product=products.find(p=>productSlug(p)===pm[1]);if(product)return {...defaults,title:`${product.name} Denim Fabric | Curva Fabric`,description:`${product.description} Review composition, weight, MOQ, lead time and request a swatch.`,image:product.image,schemaType:'product',product}}const sm=path.match(/^\/services\/(.+)$/);if(sm&&servicePages[sm[1]]){const s=servicePages[sm[1]];return {...defaults,title:`${s.title} | Curva Fabric`,description:s.intro,image:s.image,schemaType:'webpage'}}const am=path.match(/^\/news-blog\/(.+)$/);if(am){const article=articles.find(a=>a.slug===am[1]);if(article)return {...defaults,title:`${article.title} | Curva Fabric`,description:article.summary,image:article.image||defaults.image,type:'article',schemaType:'article',article}}return {...defaults,title:'Page Not Found | Curva Fabric',description:'The requested denim fabric page could not be found.',canonical:null,noindex:true}}
export function getStructuredData(seo,siteUrl=defaultSiteUrl,faqs=[]){const root=siteUrl.replace(/\/$/,'');const url=seo.canonical?`${root}${seo.canonical}`:root;const org={'@type':'Organization',name:'Curva Fabric',url:root,email:'fabric@curvadenim.com',description:'B2B denim fabric supplier for brands, garment factories and distributors.',areaServed:'Worldwide',knowsAbout:['Denim fabric','Rigid and stretch denim','Textile testing','Fabric sourcing']};if(seo.path==='/faq')return {'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};if(seo.schemaType==='organization')return {'@context':'https://schema.org',...org};if(seo.schemaType==='product'&&seo.product)return {'@context':'https://schema.org','@type':'Product',name:seo.product.name,description:seo.product.description,image:`${root}${seo.product.image}`,sku:seo.product.id,category:seo.product.category,url,audience:{'@type':'BusinessAudience',audienceType:'Apparel brands, garment factories and fabric buyers'},additionalProperty:[{'@type':'PropertyValue',name:'Fabric MOQ',value:seo.product.moq||'Confirmed by quality'},{'@type':'PropertyValue',name:'Fabric weight',value:seo.product.sizes||'Confirmed by quality'}]};if(seo.schemaType==='article'&&seo.article)return {'@context':'https://schema.org','@type':'Article',headline:seo.article.title,description:seo.article.summary,image:`${root}${seo.article.image}`,datePublished:seo.article.publishedAt,author:{'@type':'Person',name:seo.article.authorName||'Curva Fabric Team'},publisher:org};return {'@context':'https://schema.org','@type':'WebPage',name:seo.title,description:seo.description,url,audience:{'@type':'BusinessAudience',audienceType:'Fabric buyers'}}}
