import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Building2, CheckCircle2, Mail, Send } from 'lucide-react';

const initial=product=>({name:'',company:'',country:'',email:'',whatsapp:'',businessType:'apparel-brand',salesChannels:'',websiteUrl:'',targetRetailPrice:'',annualVolume:'',productCategory:'denim-fabric',specifications:product,estimatedQuantity:'',deliveryDestination:'',targetDelivery:'',message:'',website:''});

export function QuoteForm({initialProduct='',compact=false}){
  const [form,setForm]=useState(()=>initial(initialProduct));
  const [status,setStatus]=useState({sending:false,error:'',reference:''});
  useEffect(()=>{if(initialProduct)setForm(x=>({...x,specifications:initialProduct}))},[initialProduct]);
  const update=e=>setForm(x=>({...x,[e.target.name]:e.target.value}));
  const submit=async e=>{e.preventDefault();setStatus({sending:true,error:'',reference:''});try{const res=await fetch('/api/quotes/public',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const result=await res.json();if(!res.ok)throw new Error(result.message||'Unable to submit inquiry');setStatus({sending:false,error:'',reference:result.data.reference});setForm(initial(''))}catch(err){setStatus({sending:false,error:err.message,reference:''})}};
  if(status.reference)return <div className="rounded-3xl bg-[#e7efe8] p-8 text-center"><CheckCircle2 className="mx-auto text-[#2d6a4f]" size={44}/><h2 className="mt-4 font-heading text-2xl font-bold">Buyer inquiry received.</h2><p className="mt-2 text-[#56635c]">Our wholesale team will review your retail profile and assortment needs. Reference: <strong>{status.reference}</strong></p></div>;
  return <form onSubmit={submit} className={`grid gap-5 ${compact?'':'rounded-[2rem] bg-white p-6 shadow-sm sm:p-9'}`}>
    <input name="website" value={form.website} onChange={update} className="hidden" tabIndex="-1" autoComplete="off"/>
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a84d33]">1 · Buyer information</p><div className="mt-4 grid gap-5 sm:grid-cols-2">{[['name','Buyer name *','text'],['company','Company / store name *','text'],['email','Business email *','email'],['whatsapp','Phone / WhatsApp','text'],['websiteUrl','Store or company website','url'],['country','Country *','text']].map(([name,label,type])=><label key={name}><span className="mb-2 block text-sm font-semibold">{label}</span><input required={['name','company','email','country'].includes(name)} type={type} name={name} value={form[name]} onChange={update} className="w-full rounded-xl border-[#17251f]/15"/></label>)}</div></div>
    <div className="border-t border-[#17251f]/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a84d33]">2 · Company profile</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Business type *</span><select required name="businessType" value={form.businessType} onChange={update} className="w-full rounded-xl border-[#17251f]/15"><option value="apparel-brand">Apparel brand</option><option value="garment-factory">Garment factory</option><option value="fabric-distributor">Fabric distributor / agent</option><option value="designer-studio">Designer / development studio</option><option value="retailer">Retailer with private label</option></select></label><label><span className="mb-2 block text-sm font-semibold">Main products / end use *</span><input required name="salesChannels" value={form.salesChannels} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. five-pocket jeans and jackets"/></label><label><span className="mb-2 block text-sm font-semibold">Target fabric price (USD/m)</span><input name="targetRetailPrice" value={form.targetRetailPrice} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. USD 3.50–4.20/m"/></label><label><span className="mb-2 block text-sm font-semibold">Estimated annual fabric volume</span><input name="annualVolume" value={form.annualVolume} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. 50,000–100,000 meters"/></label></div></div>
    <div className="border-t border-[#17251f]/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a84d33]">3 · Fabric brief</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Fabric interest</span><select name="productCategory" value={form.productCategory} onChange={update} className="w-full rounded-xl border-[#17251f]/15"><option value="denim-fabric">Multiple denim qualities</option><option value="rigid-denim">Rigid denim</option><option value="stretch-denim">Stretch denim</option><option value="lightweight-denim">Lightweight / soft denim</option><option value="specialty-denim">Color / recycled / specialty</option></select></label><label><span className="mb-2 block text-sm font-semibold">Estimated first order (meters) *</span><input required type="number" min="1" name="estimatedQuantity" value={form.estimatedQuantity} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. 3,000"/></label><label><span className="mb-2 block text-sm font-semibold">Delivery city / country</span><input name="deliveryDestination" value={form.deliveryDestination} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. Ho Chi Minh City, Vietnam"/></label><label><span className="mb-2 block text-sm font-semibold">Target delivery window</span><input name="targetDelivery" value={form.targetDelivery} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. November 2026"/></label></div><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Composition, weight, stretch, shade and end use *</span><textarea name="specifications" required rows="4" value={form.specifications} onChange={update} className="w-full rounded-xl border-[#17251f]/15" placeholder="e.g. 11–12 oz, 99/1 cotton stretch, deep indigo, jeans, wash-down reference available"/></label><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Testing, certification, packing or other requirements</span><textarea name="message" rows="4" value={form.message} onChange={update} className="w-full rounded-xl border-[#17251f]/15"/></label></div>
    {status.error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{status.error}</p>}
    <button disabled={status.sending} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#17251f] px-7 py-4 font-semibold text-white hover:bg-[#a84d33] disabled:opacity-50"><Send size={18}/>{status.sending?'Sending…':'Request line sheet & quote'}</button>
    <p className="text-xs text-[#758079]">B2B inquiries only. Submission does not create a purchase order or guarantee pricing, capacity or delivery. Final terms are confirmed in the quotation and proforma invoice.</p>
  </form>
}

export default function Contact(){const [params]=useSearchParams();return <div className="min-h-screen bg-[#f8f4ec] pt-24"><section className="bg-[#17251f] px-5 py-16 text-center text-white"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#e8a182]">For brands, factories & fabric buyers</p><h1 className="mt-3 font-heading text-5xl font-bold">Request swatches and a fabric quote.</h1><p className="mx-auto mt-4 max-w-2xl text-white/65">Share your end use and technical targets. We’ll reply with relevant qualities, sample availability, MOQ, lead time and the information needed for quotation.</p></section><main className="mx-auto grid max-w-6xl gap-10 px-5 py-14 lg:grid-cols-[.65fr_1.35fr]"><aside><Building2 size={32} className="text-[#a84d33]"/><h2 className="mt-5 font-heading text-2xl font-bold">A useful fabric brief includes</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-[#5e6a63]">{['Garment type and target market','Composition and fabric weight','Rigid, comfort or high stretch','Indigo shade, finish and wash target','Order meters and delivery window','Testing or certification requirements'].map(x=><li key={x}>— {x}</li>)}</ul><a className="mt-7 flex items-center gap-2 font-semibold text-[#a84d33]" href="mailto:fabric@curvadenim.com"><Mail size={18}/>fabric@curvadenim.com</a></aside><QuoteForm initialProduct={params.get('product')||''}/></main></div>}

