import { Link } from 'react-router-dom';
import { ArrowRight, Boxes, ClipboardCheck, Droplets, Factory, Leaf, Ruler, ShieldCheck } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { productSlug } from '../data/seoContent';

const capabilities=[[Ruler,'Clear technical specs','Weight, composition, weave, width and stretch data for every selected quality.'],[Droplets,'Wash-development ready','Indigo shades and constructions selected around rinse, enzyme and vintage wash goals.'],[Leaf,'Responsible options','Recycled-content and lower-impact qualities supported by program-specific documentation.'],[ShieldCheck,'Lot-level quality control','Shade, weight, width, shrinkage, skew and physical performance checked to agreed standards.']];
const process=[['01','Send your fabric brief','Share end use, target weight, composition, stretch, shade, finish, quantity and delivery.'],['02','Shortlist qualities','We match stocked standards or develop options around your cost and performance targets.'],['03','Review swatches & tests','Confirm hand feel, color, wash-down, lab data, MOQ, price and commercial terms.'],['04','Approve bulk production','Bulk is produced and inspected against the approved lab dip, swatch and specification.']];

export default function HomePage(){const {state}=useStore();return <div className="min-h-screen bg-[#f8f4ec] pt-24">
<section className="relative min-h-[710px] overflow-hidden bg-[#101a22]"><img src="/fabric/hero-denim-mill.png" alt="Indigo denim rolls and fabric swatches in a textile mill" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#0d171d]/95 via-[#0d171d]/78 to-transparent"/><div className="relative mx-auto flex min-h-[710px] max-w-7xl items-center px-5 sm:px-8"><div className="max-w-2xl py-20 text-white"><p className="mb-5 text-sm font-bold uppercase tracking-[.24em] text-[#e8a182]">Denim fabric supplier · Mill-direct sourcing</p><h1 className="font-heading text-5xl font-bold leading-[.98] sm:text-7xl">Denim that starts<br/><span className="font-serif italic text-[#e8a182]">with the right cloth.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/72">Rigid, stretch, lightweight and recycled-content denim for brands, garment factories and fabric distributors—specified by weight, composition, weave and performance.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex items-center gap-2 rounded-full bg-[#b85c3f] px-7 py-4 font-semibold text-white">Request swatches <ArrowRight size={18}/></Link><Link to="/products" className="rounded-full border border-white/25 bg-white/10 px-7 py-4 font-semibold text-white backdrop-blur">Explore fabric qualities</Link></div><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-white/60"><span>7.5–13 oz core range</span><span>Rigid · Stretch · Specialty</span><span>Custom development available</span></div></div></div></section>
<section className="bg-[#17251f] text-white"><div className="mx-auto grid max-w-7xl gap-px md:grid-cols-4">{capabilities.map(([Icon,title,desc])=><div key={title} className="flex gap-4 border-white/10 p-7 md:border-r"><Icon className="shrink-0 text-[#e8a182]"/><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-white/60">{desc}</p></div></div>)}</div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#a84d33]">Core fabric library</p><h2 className="mt-2 font-heading text-4xl font-bold text-[#17251f]">Built around end use, hand feel and performance</h2><p className="mt-3 max-w-2xl text-[#657068]">Compare rigid structure, comfort stretch, lightweight drape and specialty color or recycled-content constructions.</p></div><Link to="/products" className="inline-flex items-center gap-2 font-semibold">View all fabrics <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{state.products.slice(0,6).map(product=><Link key={product.id} to={`/products/${productSlug(product)}`} className="group"><div className="relative overflow-hidden rounded-3xl bg-[#eee9e0]"><img src={product.image} alt={product.name} className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-xs font-bold text-[#a84d33]">{product.badge||'Mill quality'}</span></div><h3 className="mt-4 font-semibold text-[#17251f]">{product.name}</h3><p className="mt-1 text-sm text-[#657068]">{product.sizes} · {product.wash}</p><p className="mt-2 text-xs font-bold uppercase tracking-wider text-[#a84d33]">MOQ {product.moq}</p></Link>)}</div></section>
<section className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><Factory className="text-[#a84d33]" size={34}/><h2 className="mt-5 font-heading text-4xl font-bold">From fabric brief to approved bulk.</h2><p className="mt-5 leading-7 text-[#657068]">One workflow connects quality selection, sampling, wash trials, testing, production, inspection and export coordination.</p><Link to="/services/wholesale-private-label" className="mt-7 inline-flex items-center gap-2 font-semibold text-[#a84d33]">How fabric sourcing works <ArrowRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{process.map(([n,t,d])=><div key={n} className="rounded-3xl border border-[#17251f]/10 bg-[#fbf8f2] p-6"><span className="text-xs font-bold text-[#a84d33]">{n}</span><h3 className="mt-3 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#657068]">{d}</p></div>)}</div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid overflow-hidden rounded-[2.5rem] bg-[#315f76] text-white lg:grid-cols-[1.15fr_.85fr]"><div className="p-9 sm:p-14"><ClipboardCheck size={34} className="text-[#c8e4ef]"/><h2 className="mt-5 font-heading text-4xl font-bold">Have a fabric target in mind?</h2><p className="mt-5 max-w-xl leading-7 text-white/80">Send a reference swatch or technical brief. We’ll recommend comparable qualities and confirm sample availability, MOQ and lead time.</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 font-semibold text-[#244b5e]">Start a fabric inquiry <ArrowRight size={17}/></Link></div><div className="grid grid-cols-2 gap-px bg-white/15 p-px">{[['7.5–13 oz','Core weight range'],['1,000 m','Typical MOQ'],['25–45 days','Typical production'],['Lab testing','By agreed standard']].map(([v,l])=><div key={l} className="flex flex-col justify-center bg-[#2b566a] p-7"><strong className="font-heading text-2xl">{v}</strong><span className="mt-1 text-sm text-white/70">{l}</span></div>)}</div></div></section></div>}
