import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, X, UserRound, ClipboardList } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useStore } from '../context/StoreContext';

export default function Header(){
  const [open,setOpen]=useState(false); const location=useLocation(); const {user}=useAuth(); const {state}=useStore();
  const rfqCount=state.rfqAssortment.reduce((sum,item)=>sum+item.quantity,0);
  const nav=[['/products','Fabrics'],['/services/wholesale-private-label','Fabric Sourcing'],['/services/fit-and-size-guide','Technical Guide'],['/about','About the Mill'],['/news-blog/','Fabric Insights'],['/faq','FAQ']];
  return <><div className="fixed inset-x-0 top-0 z-[60] bg-[#17251f] py-2 text-center text-[11px] font-bold uppercase tracking-[.18em] text-white">B2B fabric supply · Global delivery · Request swatches &amp; technical data</div><header className="fixed inset-x-0 top-8 z-50 border-b border-[#17251f]/10 bg-[#fbf8f2]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" className="font-heading text-2xl font-black tracking-[-.05em] text-[#17251f]">CURVA<span className="text-[#a84d33]">FABRIC</span><small className="ml-2 hidden align-middle text-[9px] font-bold tracking-[.18em] text-[#657068] sm:inline">DENIM MILL</small></Link><nav className="hidden items-center gap-6 xl:flex">{nav.map(([path,label])=><Link key={path} to={path} className={`text-sm font-semibold ${location.pathname.startsWith(path)?'text-[#a84d33]':'text-[#34443c] hover:text-[#a84d33]'}`}>{label}</Link>)}</nav><div className="flex items-center gap-1"><Link to="/contact" className="hidden rounded-full bg-[#a84d33] px-4 py-2.5 text-sm font-semibold text-white md:block">Request Swatches</Link><Link to="/login" aria-label={user?'Buyer account':'Buyer sign in'} className="rounded-full p-2 hover:bg-black/5"><UserRound size={20}/></Link><Link to="/quote" aria-label="RFQ assortment" className="relative rounded-full p-2 hover:bg-black/5"><ClipboardList size={20}/>{rfqCount>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#a84d33] px-1 text-[10px] font-bold text-white">{rfqCount}</span>}</Link><button onClick={()=>setOpen(!open)} className="rounded-full p-2 xl:hidden" aria-label="Menu">{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="border-t bg-[#fbf8f2] px-5 py-5 xl:hidden">{nav.map(([path,label])=><Link onClick={()=>setOpen(false)} className="block py-3 font-semibold" key={path} to={path}>{label}</Link>)}<Link onClick={()=>setOpen(false)} to="/contact" className="mt-3 block rounded-full bg-[#a84d33] px-5 py-3 text-center font-semibold text-white">Request Swatches</Link></nav>}</header></>;
}
